### ISSUE TITLE
مصرف Memory

### ISSUE THREAD

**Issue by MahdiShamsDev** [sajjadmrx/btime-desktop#2]
سلام، ایده خیلی باحال و خفنیه، فقط متوجه شدم که 187 مگابایت رم اشغال میکنه.
طبیعیه؟
![Screenshot 2023-11-07 233953](https://github.com/sajjadmrx/btime-desktop/assets/56548100/893a0dc1-0939-4a94-9f35-0e82a4565377)

**Comment by ErfanTech** [comment]
![Screenshot (877)](https://github.com/sajjadmrx/btime-desktop/assets/108360299/04c5e8f0-a7f6-48eb-9c7a-872334cf66a8)
