### ISSUE TITLE
آنتی ویروس تروجان نشونش میده

### ISSUE THREAD

**Issue by creasydude** [sajjadmrx/btime-desktop#20]
آنتی ویروس تروجان نشونش میده
ویندوز دفندر ویندوز 11

**Comment by Behzad9** [comment]
من الان اسکن کردم، مشکلی نداشت. حتی فایل رو برای سایت virustotal هم فرستادم، اونم ویروس یا تروجانی پیدا نکرد. اینم نتیجه اسکن هست:

[VirusTotal Scan Result](https://www.virustotal.com/gui/file/7fe92f452e0e6c21f5c470dc3dd936932ef4f1e767e9cb66b5386597c686d292?nocache=1)
