### ISSUE TITLE
لود نکردن ارز ها موقع  بالا اومدن سیستم اگه به نت وصل نباشه

### ISSUE THREAD

**Issue by kasraargus** [sajjadmrx/btime-desktop#27]
اون اول که سیستم روشن میشه یا از اسلیپ در میاد اگه به نت وصل نباشه کلا لود نمیکنه یا یه حالتی بذاری که تنظیم کنم هر چند دقیقه یه بار لود کنه یا اینکه یه دکمه رفرش باشه هم خوبه

https://github.com/user-attachments/assets/6aa7674a-c2af-403f-b6eb-48212ab3b6ad

**Comment by sajjadmrx** [comment]
لودینگ و دکمه رفرش اضافه شد تو ورژن [v1.3.0](https://github.com/sajjadmrx/btime-desktop/releases/tag/v1.3.0)

**Comment by kasraargus** [comment]
خیلی ممنون که پیگیری و وقت میذاری 
این مشکل هنوز برای آب و هوا حل نشده 


![Uploading image.png…]()
