### ISSUE TITLE
Feature request: sliding infinite, complete calender

### ISSUE THREAD

**Issue by artadp** [sajjadmrx/btime-desktop#3]
سلام و عرض ادب
میخواستم خواهش کنم که دو فیچر اضافه کنید، یکی زمانی که بشه فلش ها رو تا بی نهایت تغییر داد، و یکسره بچرخه و مثلا وقتی روی حالت راست هستیم بزنیم راست، حالت بعدی بیاد.
بعد هم این که میخواستم خواهش کنم یک دکمه برای باز شدن یک تقویم کامل اضافه کنید. یعنی هم تقویم رو بذارید هم دکمه رو :)))
نیازمندم
از زحمتتون هم سپاسگزارم

**Comment by mr-shady** [comment]
سلام، اگر امکان این فراهم بشه که توی تسکبار هم بیاد خیلی خوبه!
همچنین بشه تنظیم کرد وقتی روی ویجت کلیک میشه یک برنامه مثل تقویم سیستم یا یه وبسایت مثل گوگل کلندر هم باز بشه عالیه!
