### ISSUE TITLE
صفحه تنظیمات

### ISSUE THREAD

**Issue by alisalehi1380** [sajjadmrx/btime-desktop#31]
سلام سجاد جان وقتت بخیر
ممنون از این ویجت فوق کاربردیت! 👌❤️
چطور میتونم به صفحه ی تنظیماتی که اولش نشون داد برم؟

![image](https://github.com/user-attachments/assets/eb749cd9-5527-40c3-8816-410630e1c0fb)

**Comment by sajjadmrx** [comment]
سلام، تو taskbar سمت چپ آیکون 🔽 رو بزن و روی آیکون برنانه کلیک راست و تنظیمات

**Comment by alisalehi1380** [comment]
گرفتم. ممنون ازت. 🙏
