### ISSUE TITLE
[BUG]: عدم تطابق تاریخ با روز های هفته

### ISSUE THREAD

**Issue by alisalehi1380** [sajjadmrx/btime-desktop#48]
سلام سجاد جان خوبی؟ 
نمیدونم این رو اطلاع دادن یا نه، ولی امروز جمعه هست و در قسمت تقویم داره با title `ش` نمایشش میده.

![image](https://github.com/user-attachments/assets/0a8184c3-5f8a-4f33-8559-e734c7f83cf6)

**Comment by sajjadmrx** [comment]
Fixed [v1.4.5](https://github.com/sajjadmrx/btime-desktop/releases/tag/v1.4.5)
