### ISSUE TITLE
نصب شدن اپ‌دیتا به جای پروگرام‌فایلز

### ISSUE THREAD

**Issue by xmha97** [sajjadmrx/btime-desktop#5]
سلام، پیشنهاد می‌کنم اینستالر را تغییر دهید که به جای Program Files در AppData برنامه را نصب کند.
یا حداقل به کاربر حق انتخاب بدید:
![image](https://github.com/sajjadmrx/btime-desktop/assets/23485114/8bd146a5-e5ac-47a6-9fc3-0837481dfe05)
چرا؟ چون نصب شدن در Program Files نیازمند دسترسی ادمین است و این باعث می‌شود که کاربرانی که دسترسی ادمین ندارند، نتوانند برنامه را نصب کنند، مثلا بر روی سیستم‌های کاری

**Comment by sajjadmrx** [comment]
added [v1.2.1](https://github.com/sajjadmrx/btime-desktop/releases/tag/v1.2.1)
