### ISSUE TITLE
غیرفعال کردن اف ۱۱

### ISSUE THREAD

**Issue by xmha97** [sajjadmrx/btime-desktop#9]
سلام
با فشردن دکمه‌ی F11 برنامه فول‌اسکرین میشه!

رفتار در نسخه‌ی [1.0.2](https://github.com/sajjadmrx/btime-desktop/releases/tag/v1.0.2):

https://github.com/sajjadmrx/btime-desktop/assets/23485114/1879200c-333c-4684-92a9-32fd3e5b78a4

**Comment by sajjadmrx** [comment]
سلام، ممنون بابت گذارش ها
چشم تو اپدیت جدید مواردی که گفتید رفع/اضافه میشه

**Comment by xmha97** [comment]
رفتار در نسخه‌ی 1.0.4

https://github.com/sajjadmrx/btime-desktop/assets/23485114/d22a9e08-67d2-4d53-b91b-efcc600b5e38
